### ISSUE TITLE
Wallet Balance Update Bug

### ISSUE THREAD

**Issue by maemon** [litecoin-foundation/LoafWallet#20]
The balance on the wallet wouldn't update when you get litecoins from shapeshift.io, even after multiple confirmations.

It does however update itself once you spend some coins on the app.

Testing Device: Iphone 7 & Iphone SE

Balance Before Spending: https://drive.google.com/open?id=0ByUqIwz6FS4kWjFGV0RZeFJidkpla3BwN1NxamtOMUswblRv

Balance After Spending: https://drive.google.com/open?id=0ByUqIwz6FS4kb0luaXY0eFJoMHBjQmlxSWhCUU1udlNtZExn

**Comment by losh11** [comment]
Thanks for reporting this. I'll take a look, and will let you know if I am able to reproduce this. Is it only shapeshift.io?

**Comment by maemon** [comment]
Let me try some other exchanges, ill let you know :)

**Comment by maemon** [comment]
Hey losh, were you able to reproduce this?

**Comment by losh11** [comment]
Wasn't able to reproduce this. Did you manage to try other exchanges/shapeshift again?

**Comment by maemon** [comment]
yup, it happens for me everytime i use shapeshift, heres the most recent screenshot:

Before Spending: https://drive.google.com/open?id=0ByUqIwz6FS4kNG9PTEZOQlU5bXh4b2VnNUhDX0JocFJEcE5J
Tx: https://drive.google.com/open?id=0ByUqIwz6FS4kbkRuQ192N2V4WHk3Sll2c0JWZzVvNzVua3RJ

After Spending: https://drive.google.com/open?id=0ByUqIwz6FS4kbnVVZEZmMzdhTkE3TDFxLXpJNDU2NHRKQ0Nr

I'll try poloniex tomorrow and post my results.

**Comment by losh11** [comment]
Would you be able to force close the app between conf time?

**Comment by losh11** [comment]
Should be resolved in the 1.0.2 update being released in a day or two.
