### ISSUE TITLE
iCloud backup Wallet seed

### ISSUE THREAD

**Issue by bearpig** [litecoin-foundation/LoafWallet#23]
As Loaf/Bread Wallet uses something on the device as a seed for the wallet creation, do you know if replacing the processor in the phone will maintain whatever is used for this seed (Device ID/IMEI/serial number)?

I've had a phone die on me, and don't have the recovery phrase for the wallet. The phone is currently stuck in recovery mode and is returning an error that is consistent with a processor failure. I can get the processor replaced which would allow the phone to boot and for me to recover from iCloud but if it's not going to rebuild the same wallet, then I won't go ahead with it.

Any help is appreciated.

**Comment by losh11** [comment]
Do you have the 12 word seed (passphrase) that was generated when you first
used LoafWallet. With that 12 word seed, you can restore your wallet.

If you are able to get someone to replace your iPhone's processor and
unlock your phone without restoring, then there would be a somewhat high
chance that you are able to recover your wallet. At any point, if you end
up restoring your device, you will loose all of your coins, as LoafWallet
does not back up your seed/private keys to iCloud (for obvious reasons).


If you do end up recovering your wallet, please make sure that you go into
settings and then copy down your 12 word seed, just in case anything like
this happens in the future.

**Comment by bearpig** [comment]
Hi losh11, 
Thanks for the quick reply.
I'd assumed that the iCloud backups would work in a similar way to Bread wallets method ([as stated here](https://www.reddit.com/r/breadwallet/comments/3xlu70/is_it_possible_to_restore_a_wallet_without_a/cypvb2w/) ).
