### ISSUE TITLE
Support for new address format

### ISSUE THREAD

**Issue by adno** [litecoin-foundation/LoafWallet#26]
The current version does not seem to support the new address format starting with a "3". I was unable to scan a QR code of one such adress (nothing happened when I pointed at the QR code which was clearly visible).

**Comment by losh11** [comment]
The latest P2SH prefix for mainnet is: `M` and testnet: `Q`.
You can use this converter to convert addresses between prefixes: http://litecoin-project.github.io/p2sh-convert/

**Comment by adno** [comment]
My bad, `3` is the old prefix. It meant I could not pay using Loafwallet nonetheless. What about asking the user if they want to send to an old format address and offering to convert it? Scanning a QR code in a separate app, converting it in using a web form to the new format, and then pasting back to wallet is silly and error-prone.
