### ISSUE TITLE
Nothing happens!!! waiting for confirmation for hours now....

### ISSUE THREAD

**Issue by Ben3105** [litecoin-foundation/LoafWallet#28]
Dear all, can someone please help me!
This evening I installed the latest version of loaf wallet on my Iphone. Then I imported my Private Key to the wallet. Then I sent the LTC from my Paper-Wallet Adress LiUreF6hH99AhckdN3AqMWdcZfhhdCx56Z to the Wallet Adress in LoafWallet LUaLUEqR3Y1CsMyMbqWzosMowYp24LZ9iJ. Loaf Wallet shows that this transaction was verified in Block #1243500. Within a minute all the transfered LTC was on the LoafWallet. 
The ID for this transaction is: 645bf94350a8af5661f8d2c313e0f4dfa0770461c48c7465cc861969d190d823 

Then I sent the LTC from the LoafWallet to my Kraken adress, which is LWeTRUhq8bnpcvZCkp58KZm1CMzxbB3fMg. Since then: NOTHING happened. The Wallet shows status: waiting for verification for three hours now... 0 confirmations yet. ID of this transaction is 551feec842a09d8bfc6b54b9a3807ef909819027acb0e3d2f840dd8dce0f56c4. 

I have a panic now that all my BTC is gone and that LoafWallet isn't working?
Would someone please help me?

Kind regards, Ben

**Comment by losh11** [comment]
Hi. Please do not panic, your Litecoin is not lost. Today there was a spam attack on the Litecoin blockchain, congesting the entire network. Due to that, LoafWallet must have created a transaction where the fees were not high enough for your transaction to confirm quickly. 

Please scan your blockchain from within the LoafWallet menu. Eventually your transaction should confirm and appear to be sent. It may take a while for that to happen. 

Today during the spam attack, I sent myself some coins. Due to the spam attack, it took around 6 hours for the transaction to first report as confirmed.

**Comment by Ben3105** [comment]
Hi, this is kind of strange... I transfered (with the same amaount of transaction fee) only one minute before this not working transaction from my paper wallet to the loaf wallet. Everything worked perfectly and quick. It has bee over 9 hours now. Nothing happend. 
In the chapter "pull adresse" there is a message "LoafWallet will now validate new and legacy P2SH address formats #27" that states that Loaf-wallet is not able to send to Kraken for the moment? If so, what will happen if Karaken do not accept my debit?!

**Comment by Ben3105** [comment]
Please have a look at my screenshot. My LTCs should be still at my current loafwallet adress?? There is no transaction to my kraken account shown...
![1](https://user-images.githubusercontent.com/30328353/28449574-63336f6c-6de1-11e7-9295-99fdb175c58e.JPG)

If so how can I get my private key for this walle adress at loafwallet?
Thanks in advance, Ben

**Comment by Ben3105** [comment]
10 hours now. scanned blockchain one again... nothing happened

**Comment by Ben3105** [comment]
Dear @losh11 , I'm sure you really have a lot to do besides my "problem" but could you please have a closer look to my problem? Nothing has happend yet and >15 hours are gone now... I really don't know whom to ask instead... I really apriciate your help!. Kind regards, Ben

**Comment by losh11** [comment]
Can you email me at loshan1212@gmail.com?

**Comment by Ben3105** [comment]
I fixed the problem myself. Thanks.
