### ISSUE TITLE
Display wallet balance in local currency

### ISSUE THREAD

**Issue by tanx** [litecoin-foundation/LoafWallet#31]
First of all thanks for the nice app and your amazing work. The only feedback I have is that it would be nice to have the current wallet balance in the app header be displayed in the local currency as well (just like in BreadWallet). This makes it easy to see at a glance how much Litecoins I own. Like so:

`0,11676083 L (5,00 €)`

**Comment by losh11** [comment]
There's an updated design being released in LoafWallet v2, which will be released in a few days.
