### ISSUE TITLE
Testing import of paper wallet advises "this private key is empty"

### ISSUE THREAD

**Issue by pwrdwnsys** [litecoin-foundation/LoafWallet#35]
Before moving my coins around, I wanted to be sure that I could recover them using a process I had practiced. I created a new paper wallet with a BIP38 passphrase [here](https://bitcoinpaperwallet.com/bitcoinpaperwallet/generate-wallet.html?design=alt-litecoin#) and then attempted to import the private key into LoafWallet on iOS. After scanning the QR code, I was prompted for the passphrase which I input and then a message appeared with "this private key is empty". I tried the same with a non-BIP38 private key and the same message appeared. As there is a zero balance on that wallet, if this error on import is by design can the message be modified to explain why e.g. "You cannot import a wallet with a zero balance" or perhaps documentation to explain the reason. Or should attempting to import a zero-balance wallet result in a different outcome?

**Comment by losh11** [comment]
Should be fixed in LoafWallet v2.
