### ISSUE TITLE
Ltc sent from onlinewallet (cyrueo.net) to loafwallet

### ISSUE THREAD

**Issue by Endrit97** [litecoin-foundation/LoafWallet#37]
Hi, 
I have a problem with the loafwallet app.
Ive sent 17$-worth ltc from my onlinewallet to loafwallet, but its still not recieving the transaction.

**Comment by losh11** [comment]
Can you share your transaction ID?

**Comment by Endrit97** [comment]
I just have the recieving address,
LVaV61Qu9ub1ZdT4o6nA6FNR8S1uKEQ7s2

**Comment by Endrit97** [comment]
Can anyone help me?

**Comment by losh11** [comment]
Please share a specific transaction id (txid). A new receiving address is regenerated every time you open the app.

**Comment by Endrit97** [comment]
https://prnt.sc/gyum0b

i think you misunderstood me, the txid is the recieving addres in this case, the txid on the app wont show up because the money did not show up

**Comment by Endrit97** [comment]
It would be nice if i get any answer, is this normal here?

**Comment by gabrieldov** [comment]
You received help, someone asked for the TXid... the problem is this is not related to LoafWallet, but probably to the wallet where you sent the money from - since it never reached the LoafWallet or was propagated to the network as you stated. You should look for support from the sending wallet - since apparently they failed to send your transaction. Do you control the keys to that wallet?

**Comment by gabrieldov** [comment]
Anyone knows the wallet "cyrueo.net" ??? Where did you get that from? I don't see at the official websites any link to it.

**Comment by Endrit97** [comment]
Im starting to think that the cyrueo.net is a scamsite, i searched for a secure onlinewallet and it looked secure... till now

**Comment by gabrieldov** [comment]
Looks like a scam site to me too. Needs to be reported. Share your experience at some scam website reviews website so others don't fall for it.

**Comment by Dideki** [comment]
Dear Everybody! 
Sorry my bad English.
![cyrueo](https://user-images.githubusercontent.com/11036159/31981177-c8bebcfe-b951-11e7-80f2-50c5789a5fc8.jpg)
10 days ago I registered cyrueo.net, I want quickly a LTC wallet, I searching in google, it first hit. I asked for a payment, but recipient not receive.
I wrote for support several times. First when I write, few days ago support asked about my LTC address, I send, then no answer. 3 days ago this was written:
"Support Agent 21 October 2017, 16:17
Hello, hmm. We sent a notification to our developers about this issue"

If anyone can help, write. Thanks.

**Comment by Dideki** [comment]
Another site: https://curyoky.net/en/login
original curyoky.net redirected to nextether.com

**Comment by gabrieldov** [comment]
Only use wallets recommended at official websites such as litecoin.com or litecoin.org - all other sources/wallets could be compromissed and unchecked, you might end up losing coins to a scam

**Comment by losh11** [comment]
Removing this issue since this is unrelated to LoafWallet.
